name: First CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
     

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile Java
        run: javac HelloWorld.java

      - name: Run Java
        run: java HelloWorld

      - name: Show files
        run: ls -l

      - name: Print Hello
        run: echo "Hello CI/CD 🚀"
